### ISSUE TITLE
Epd output

### ISSUE THREAD

**Issue by Negatil07** [fairy-stockfish/bookgen#3]
Cannot find or it maybe not save book.epd file on Droidfish.
![Screenshot_20230125-162806](https://user-images.githubusercontent.com/97826921/214513577-d05beb4c-0d4a-4813-a769-2c84b0e36d2e.png)
or
![Screenshot_20230125-163008](https://user-images.githubusercontent.com/97826921/214513934-5f10c20c-9f7a-4d7b-afbd-bec8dd3f9878.png)

**Comment by ianfab** [comment]
Since the book generation uses commands that are outside the UCI specification, see e.g. https://github.com/fairy-stockfish/bookgen/wiki/Examples#4-ply-book-for-standard-chess, you won't be able to generate a book using a standard UCI GUI like Droidfish. The standard way of using it is using the command line, but I have never tried to use it on android to be honest.
